configs:
- id: auto-log-cron-ingest
  config:
    name: 
      type: environment
      name: cron_name
    template: log-ingest.json
    parameters:
      namespace: 
        type: environment
        name: namespace
      log_source_filter:
        type: environment
        name: cron_name
  type:
    settings:
      schema: builtin:logmonitoring.log-storage-settings
      schemaVersion: "1"
      scope: environment
- id: auto-log-cron-alert
  config:
    name: 
      type: environment
      name: cron_name
    template: metric-event.json
    parameters:
      metric_key: 
        type: environment
        name: cron_name
      threshold:
        type: environment
        name: threshold
  type:
    settings:
      schema: builtin:anomaly-detection.metric-events
      schemaVersion: 1.0.9
      scope: environment
- id: auto-log-cron-metric
  config:
    name: 
      type: environment
      name: cron_name
    template: log-metric.json
    parameters:
      source_match_string:
        type: environment
        name: cron_name
      content_match_string:
        type: environment
        name: matcher
      log_key:
        type: environment
        name: cron_name
  type:
    settings:
      schema: builtin:logmonitoring.schemaless-log-metric
      schemaVersion: 8.0.47
      scope: environment
